/*
       CREATE THE DATABASE AND TABLES
*/
DROP DATABASE IF EXISTS `STAR`;

CREATE DATABASE `STAR`;

/*CHOOSE THE DATABASE*/
USE `STAR`;

/*THE USER TABLE*/
DROP TABLE IF EXISTS `USER`;

CREATE TABLE `USER` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `USER_NICK_NAME` VARCHAR(15),
  `USER_TYPE` INT NOT NULL DEFAULT 0,
  `USER_SEX` CHAR NOT NULL DEFAULT 'N',
  `USER_PHONE` VARCHAR(11),
  `USER_EMAIL` VARCHAR(100),
  `USER_LEVEL` INT NOT NULL DEFAULT 0,
  `USER_STATUS` BOOLEAN DEFAULT FALSE ,
  `USER_SCORE` REAL DEFAULT 0.0,
  `USER_CREDIT_SCORE` REAL DEFAULT 100.0
);

/*THE WORK TABLE*/
DROP TABLE IF EXISTS `WORK`;

CREATE TABLE `WORK`(
  `WORK_ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  `WORK_NAME` VARCHAR(100) NOT NULL ,
  `WORK_OF_USER_ID` INT REFERENCES `USER`(`USER_ID`),
  `WORK_TYPE` INT NOT NULL DEFAULT 0,
  `WORK_URL` TEXT,
  `WORK_SIZE` REAL NOT NULL DEFAULT 0.0,
  `WORK_DATE` DATE,
  `WORK_HOT_VALUE` REAL DEFAULT 0.0,
  `WORK_LIKED_COUNT` INT DEFAULT 0,
  `WORK_DISLIKE_COUNT` INT DEFAULT 0
);

/*THE COMMENT TABLE*/
DROP TABLE IF EXISTS `COMMENT`;

CREATE TABLE `COMMENT`(
  `COMMENT_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `FROM_USER_ID` INT NOT NULL REFERENCES `USER`(`USER_ID`),
  `TO_USER_ID` INT REFERENCES `USER`(`USER_ID`),
  `WORK_ID` BIGINT NOT NULL REFERENCES `WORK`(`WORK_ID`),
  `COMMENT_CONTENT` VARCHAR(100) NOT NULL ,
  `COMMENT_DATE` DATE,
  `COMMENT_STATUS` BOOLEAN DEFAULT TRUE
);

/*THE REPORT_USER TABLE*/
DROP TABLE IF EXISTS `REPORT_USER`;

CREATE TABLE `REPORT_USER`(
  `REPORT_ID` BIGINT AUTO_INCREMENT PRIMARY KEY ,
  `FROM_USER_ID` INT REFERENCES `USER`(`USER_ID`),
  `TO_USER_ID` INT REFERENCES `USER`(`USER_ID`),
  `REPORT_CONTENT` VARCHAR(100) NOT NULL
);

/*THE REPORT_COMMENT TABLE*/
DROP TABLE IF EXISTS `REPORT_COMMENT`;

CREATE TABLE `REPORT_COMMENT`(
  `REPORT_ID` BIGINT AUTO_INCREMENT PRIMARY KEY ,
  `FROM_USER_ID` INT REFERENCES `USER`(`USER_ID`),
  `COMMENT_ID` BIGINT REFERENCES `COMMENT`(`COMMENT_ID`),
  `REPORT_CONTENT` VARCHAR(100) NOT NULL
);

/*THE REPORT_WORK TABLE*/
DROP TABLE IF EXISTS `REPORT_WORK`;

CREATE TABLE `REPORT_WORK`(
  `REPORT_ID` BIGINT AUTO_INCREMENT PRIMARY KEY ,
  `FROM_USER_ID` INT REFERENCES `USER`(`USER_ID`),
  `WORK_ID` BIGINT REFERENCES `WORK`(`WORK_ID`),
  `REPORT_CONTENT` VARCHAR(100) NOT NULL
);


/*INIT THE DATABASE*/

INSERT INTO `USER`(`USER_NICK_NAME`,`USER_SEX`,`USER_EMAIL`) VALUES ('joe','m','joe@gmail.com');
INSERT INTO `USER`(`USER_NICK_NAME`,`USER_SEX`,`USER_EMAIL`) VALUES ('pong','w','pong@gmail.com');
INSERT INTO `USER`(`USER_NICK_NAME`,`USER_SEX`,`USER_EMAIL`) VALUES ('tong','m','tong@gmail.com');
INSERT INTO `USER`(`USER_NICK_NAME`,`USER_SEX`,`USER_EMAIL`) VALUES ('tiny','w','t@gmail.com');
INSERT INTO `USER`(`USER_NICK_NAME`,`USER_SEX`,`USER_EMAIL`) VALUES ('bob','m','bob@gmail.com');
INSERT INTO `USER`(`USER_NICK_NAME`,`USER_SEX`,`USER_EMAIL`) VALUES ('fob','m','fo@gmail.com');
INSERT INTO `USER`(`USER_NICK_NAME`,`USER_SEX`,`USER_EMAIL`) VALUES ('lu','w','jlulu@gmail.com');
INSERT INTO `USER`(`USER_NICK_NAME`,`USER_SEX`,`USER_EMAIL`) VALUES ('kfs','m','kkk@gmail.com');
INSERT INTO `USER`(`USER_NICK_NAME`,`USER_SEX`,`USER_EMAIL`) VALUES ('zhu','m','zhu@gmail.com');
INSERT INTO `USER`(`USER_NICK_NAME`,`USER_SEX`,`USER_EMAIL`) VALUES ('hu','w','hulu@gmail.com');
INSERT INTO `USER`(`USER_NICK_NAME`,`USER_SEX`,`USER_EMAIL`) VALUES ('zui','m','zui@gmail.com');
INSERT INTO `USER`(`USER_NICK_NAME`,`USER_SEX`,`USER_EMAIL`) VALUES ('mao','w','mmmao@gmail.com');

INSERT INTO `WORK`(`WORK_NAME`,`WORK_OF_USER_ID`,`WORK_SIZE`) VALUES ('a sample I/O library: OkIo',1,1.2);
INSERT INTO `WORK`(`WORK_NAME`,`WORK_OF_USER_ID`,`WORK_SIZE`) VALUES ('okHttp,based on okIo.',1,1.1);
INSERT INTO `WORK`(`WORK_NAME`,`WORK_OF_USER_ID`,`WORK_SIZE`) VALUES ('how to let libRec work',4,2.1);
INSERT INTO `WORK`(`WORK_NAME`,`WORK_OF_USER_ID`,`WORK_SIZE`) VALUES ('The Storm platform',6,3.2);
INSERT INTO `WORK`(`WORK_NAME`,`WORK_OF_USER_ID`,`WORK_SIZE`) VALUES ('wow,the tiny man do it',0,10.5);
INSERT INTO `WORK`(`WORK_NAME`,`WORK_OF_USER_ID`,`WORK_SIZE`) VALUES ('reading is powerful',7,0.3);
INSERT INTO `WORK`(`WORK_NAME`,`WORK_OF_USER_ID`,`WORK_SIZE`) VALUES ('cute girl:L.Hao',10,2.4);

INSERT INTO `COMMENT`(`FROM_USER_ID`,`WORK_ID`,`COMMENT_CONTENT`) VALUE (9,0,'very good paper');
INSERT INTO `COMMENT`(`FROM_USER_ID`,`WORK_ID`,`COMMENT_CONTENT`) VALUE (8,1,'libRec is powerful,mark it');
INSERT INTO `COMMENT`(`FROM_USER_ID`,`WORK_ID`,`COMMENT_CONTENT`) VALUE (5,2,'big data flow processing platform');
INSERT INTO `COMMENT`(`FROM_USER_ID`,`WORK_ID`,`COMMENT_CONTENT`) VALUE (2,5,'just do it!');
INSERT INTO `COMMENT`(`FROM_USER_ID`,`WORK_ID`,`COMMENT_CONTENT`) VALUE (3,5,'wow!');
INSERT INTO `COMMENT`(`FROM_USER_ID`,`WORK_ID`,`COMMENT_CONTENT`) VALUE (6,5,'my god,so beautiful girl!');
INSERT INTO `COMMENT` (`FROM_USER_ID`,`TO_USER_ID`,`WORK_ID`,`COMMENT_CONTENT`) VALUES (10,9,0,'yes');
INSERT INTO `COMMENT` (`FROM_USER_ID`,`TO_USER_ID`,`WORK_ID`,`COMMENT_CONTENT`) VALUES (7,2,5,'so do I...');




